name: megadetector-docs

channels:
- conda-forge
- pytorch

dependencies:
- python=3.11
- sphinx
- sphinx-mdinclude
- sphinx_rtd_theme
- numpy
- Pillow
- tqdm
- jsonpickle
- humanfriendly
- matplotlib
- opencv
- requests
- scikit-learn
- pandas
- python-dateutil
- send2trash
- dill
- pytest
- pytorch::pytorch
- pytorch::torchvision
- pip
- pip:
  - fastquadtree
  - sphinx-argparse-cli
  - myst-parser
  - linkify-it-py
