name: cameratraps-detector-opencv-headless

channels:
  - conda-forge
  - pytorch
  - fastai

dependencies:
  - python=3.8.15
  - Pillow=9.1.0 
  - tqdm=4.65.0
  - jsonpickle=3.0.0
  - humanfriendly=10.0
  # Using yolov5's val.py (which is still experimental) for MDv5.0 requires a version
  # of YOLOv5 that uses np.int, which was removed as of numpy 1.24.0
  - numpy=1.23.5
  - matplotlib=3.7.1
  - opencv-python-headless=4.7.0.72
  - requests=2.31.0
  - pyqtree=1.0.0
  - scikit-learn=1.2.2

  # So we can run Jupyter notebooks in this environment
  - nb_conda_kernels=2.3.1
  - ipykernel=6.23.0
  
  # For running MegaDetector v5
  - pandas=2.0.1
  - PyYAML=6.0
  # Not used directly, but used by YOLOv5 imports
  - seaborn>=0.11.0
  - pytorch::pytorch=1.10.1
  - pytorch::torchvision=0.11.2
  - conda-forge::cudatoolkit=11.3
  - conda-forge::cudnn=8.1

  # For running MegaDetector v4
  # - tensorflow>=2.0  

  
